// arrays for use with parsing indexes from database to string names and vice-versa
const races = [
  "Dwarf",
  "Elf",
  "Halfling",
  "Human",
  "Dragonborn",
  "Gnome",
  "Half-Elf",
  "Half-Orc",
  "Tiefling"
];
const charClasses = [
  "Barbarian",
  "Bard",
  "Cleric",
  "Druid",
  "Fighter",
  "Monk",
  "Paladin",
  "Ranger",
  "Rogue",
  "Sorcerer",
   "Warlock",
   "Wizard"
];

class Character {
  constructor(name, race, charClass, abilities) {
    this.name = name;
    this.race  = race;
    this.charClass = charClass;
    this.abilities = abilities;
  }
// returns random value for single character ability using the same logic as specified in D&D Player's Handbook
// roll four six-sided dice, sum three highest rolls (possible numbers 3 - 18)
 getAbility = () => {
  const abilities = [];

  for(let i = 0; i < 4; i++) {
    abilities.push(Math.floor(Math.random() * 6) + 1);
  }

  abilities.sort((a, b) => b - a);

  return abilities[0] + abilities[1] + abilities[2];
}

// returns array of six abilities in descending order to be used in random character generation as specified in D&D Player's Handbook
// abilities randomly generated by getAbility function, so possible return values is array with six numbers each from 3 - 18 inclusive
 getAbilities = () => {
  console.log('getting abilities');
  const abilities = [];

  for(let i = 0; i < 6; i++) {
    abilities.push(getAbility());
  }
  abilities.sort((a, b) => b - a);
  console.log(abilities);
  return abilities;
}


 updateCharacter = (race, charClass) => {
  console.log('updating character');
  const abilityChoices = getAbilities();
  console.log(`ability choices: ${abilityChoices}`);
  const abilities = [];

  switch (charClass) {
    case 0: //barbarian
      abilities[0] = abilityChoices[0];
      abilities[1] = abilityChoices[2];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[5];
      abilities[4] = abilityChoices[4];
      abilities[5] = abilityChoices[3];
      break;
    case 1: //bard
      abilities[0] = abilityChoices[5];
      abilities[1] = abilityChoices[1];
      abilities[2] = abilityChoices[2];
      abilities[3] = abilityChoices[4];
      abilities[4] = abilityChoices[3];
      abilities[5] = abilityChoices[0];
      break;
    case 2: //cleric
      abilities[0] = abilityChoices[1];
      abilities[1] = abilityChoices[3];
      abilities[2] = abilityChoices[2];
      abilities[3] = abilityChoices[5];
      abilities[4] = abilityChoices[0];
      abilities[5] = abilityChoices[4];
      break;
    case 3: //druid
      abilities[0] = abilityChoices[4];
      abilities[1] = abilityChoices[5];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[2];
      abilities[4] = abilityChoices[0];
      abilities[5] = abilityChoices[3];
      break;
    case 4: //fighter
      abilities[0] = abilityChoices[0];
      abilities[1] = abilityChoices[2];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[3];
      abilities[4] = abilityChoices[4];
      abilities[5] = abilityChoices[5];
      break;
    case 5: //monk
      abilities[0] = abilityChoices[3];
      abilities[1] = abilityChoices[0];
      abilities[2] = abilityChoices[2];
      abilities[3] = abilityChoices[5];
      abilities[4] = abilityChoices[1];
      abilities[5] = abilityChoices[4];
      break;
    case 6: //paladin
      abilities[0] = abilityChoices[0];
      abilities[1] = abilityChoices[3];
      abilities[2] = abilityChoices[2];
      abilities[3] = abilityChoices[5];
      abilities[4] = abilityChoices[4];
      abilities[5] = abilityChoices[1];
      break;
    case 7: //ranger
      abilities[0] = abilityChoices[2];
      abilities[1] = abilityChoices[0];
      abilities[2] = abilityChoices[3];
      abilities[3] = abilityChoices[5];
      abilities[4] = abilityChoices[1];
      abilities[5] = abilityChoices[4];
      break;
    case 8: //rogue
      abilities[0] = abilityChoices[4];
      abilities[1] = abilityChoices[0];
      abilities[2] = abilityChoices[3];
      abilities[3] = abilityChoices[1];
      abilities[4] = abilityChoices[5];
      abilities[5] = abilityChoices[2];
      break;
    case 9: //sorcerer
      abilities[0] = abilityChoices[5];
      abilities[1] = abilityChoices[3];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[2];
      abilities[4] = abilityChoices[4];
      abilities[5] = abilityChoices[0];
      break;
    case 10: //warlock
      abilities[0] = abilityChoices[3];
      abilities[1] = abilityChoices[2];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[4];
      abilities[4] = abilityChoices[5];
      abilities[5] = abilityChoices[0];
      break;
    case 11: //wizard
      abilities[0] = abilityChoices[5];
      abilities[1] = abilityChoices[2];
      abilities[2] = abilityChoices[1];
      abilities[3] = abilityChoices[0];
      abilities[4] = abilityChoices[4];
      abilities[5] = abilityChoices[3];
      break;
  }

  console.log(`abilities after class update: ${abilities}`);

  switch (race) {
    case 0: //dwarf
      abilities[2] += 2;
      break;
    case 1: //elf
      abilities[1] += 2;
      break;
    case 2: //halfling
      abilities[1] += 2;
      break;
    case 3: //human
      abilities[0] += 1;
      abilities[1] += 1;
      abilities[2] += 1;
      abilities[3] += 1;
      abilities[4] += 1;
      abilities[5] += 1;
      break;
    case 4: //dragonborn
      abilities[0] += 2;
      abilities[5] += 1;
      break;
    case 5: //gnome
      abilities[3] += 2;
      break;
    case 6: //half-elf
      abilities[5] += 2;
      break;
    case 7: //half-orc
      abilities[0] += 2;
      abilities[2] += 1;
      break;
    case 8: //tiefling
      abilities[3] += 1;
      abilities[5] += 2;
      break;
    }

    console.log(`abilities finished: ${abilities}`);
    return abilities;
  }
}

test = new Character("JOHN!", 4, 4, [0,1,2,3,4,5]);
console.log(test);
